Traceback (most recent call last):
  File "/home/alfa/ownCloud/dev/littlecheck/littlecheck/littlecheck.py", line 735, in <module>
    main()
  File "/home/alfa/ownCloud/dev/littlecheck/littlecheck/littlecheck.py", line 715, in main
    ret = check_path(path, subs, config, TestFailure.print_message)
  File "/home/alfa/ownCloud/dev/littlecheck/littlecheck/littlecheck.py", line 646, in check_path
    return check_file(fd, path, subs, config, failure_handler)
  File "/home/alfa/ownCloud/dev/littlecheck/littlecheck/littlecheck.py", line 622, in check_file
    checker = Checker(name, lines)
  File "/home/alfa/ownCloud/dev/littlecheck/littlecheck/littlecheck.py", line 602, in __init__
    raise CheckerError("Command could not be found: " + cmd)
__main__.CheckerError: Command could not be found: /bin/fart
