Failure in python_extra_output.py:
Extra output after checks:
  Output line stdout:2: Second
